#theme:
title: Website
description: ecmajs-auth-for-static-website-jekyll
url: https://ecmajs.github.io
author: EcmaJS
google_analytics: UA-212804240-2
plugins:
  - jekyll-seo-tag

contents_root_path: /website/
contents_pages_path: /website/app/pages/